### ISSUE TITLE
where is the data file

### ISSUE THREAD

**Issue by phtmkid** [DynamicaLab/code-dynalearn#2]
When I use the jupyter nodebook code in folder notebooks/figures/manuscript-figureXXX，It says that there has a path "../../data/case-study/summaries". But I could't find it anywhere.Could you give me some suggestions?

**Comment by phtmkid** [comment]
where is the spain covid-19 data? Anyone can help me?

**Comment by charlesmurphy1** [comment]
Hi phtmkid, I am sorry for the delay.

The data files to run all the figure notebooks need to be generated before you can generate the figures. They are not available in the repository, as they are pretty sizable, but you can regenerate all the data used in the paper. I refer you to the script directory of the repository for that purpose.

Concerning the COVID-19 data, they are available in another repository, called (data-dynalearn)[https://github.com/DynamicaLab/data-dynalearn]. If you have any issues with the data itself, please create an issue in the other repository.

To close this issue, I have updated the ReadMe.md file and added more details as to where the COVID-19 data is located. I also reorganized the scripts such that they are now labeled with the figures they actually generate.

Thanks for the feedback!
